site_name: Foundry Docs
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    - scheme: default
      primary: blue grey
      accent: lime
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
copyright: Copyright &copy; 2023 Carnegie Mellon University
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cmu-sei
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/cmusei
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sei_cmu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/software-engineering-institute/