# Project information
site_name: Foundry Documentation

# Configuration
theme:
  name: material
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy

  palette:
    - scheme: default
      primary: blue grey
      accent: lime
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree navigation
nav:
- Home: index.md
- Identity Guide:
  - About Identity: identity/index.md
  - Getting started with Identity: identity/getting-started.md
  - Logging in with user account: identity/user-account-login.md
  - Identity Home: identity/home.md
  - Identity Grants: identity/grants.md
  - Identity Profile: identity/profile.md
  - Identity Integration: identity/integration.md
  - Identity Accounts: identity/accounts.md
- TopoMojo Guide:
  - About TopoMojo: topomojo/index.md
  - Getting started with TopoMojo: topomojo/getting-started.md
  - Finding an existing space: topomojo/finding-a-space.md
  - Building a new space:
    - Settings and Templates: topomojo/building-a-workspace.md
    - Document: topomojo/lab-document.md
    - Challenge: topomojo/challenge.md
    - Files: topomojo/files.md
    - Play: topomojo/play.md
  - Admin features:
    - Admin Dashboard: topomojo/admin-dashboard.md
    - Gamespaces: topomojo/admin-gamespaces.md
    - Workspaces: topomojo/admin-workspaces.md
    - Templates: topomojo/admin-templates.md
    - Machines: topomojo/admin-machines.md
    - Users: topomojo/admin-users.md
    - Log: topomojo/admin-log.md    
  - Copy and paste: topomojo/copy-paste.md
- Gameboard Guide:
  - About the Gameboard: gameboard/index.md
  - Participating in a game: gameboard/participating.md
  - Practicing challenges: gameboard/practice-area.md
  - Using integrated support: gameboard/support.md
  - Using Reports: gameboard/reports-beta.md
  - Administering games: 
    - Administration: gameboard/admin.md
    - Practice: gameboard/admin-practice-area.md
    - Roles: gameboard/admin-roles.md
    - Players: gameboard/admin-players.md
    - Observe mode: gameboard/admin-observe.md
    - Settings: gameboard/admin-settings.md
    - Feedback form: gameboard/admin-feedback-form.md
    - Completion Certificates: gameboard/completion-certificates.md
    - Clone, yaml, and json options: gameboard/admin-clone-yaml-json.md
- Cubespace Instructor Guide:
  - Cubespace Getting Started: cubespace-instructor/0-ins-getting-started.md
  - The Dauntless Manual: cubespace-instructor/ins-dauntless-manual.md
  - In-game/Out-of-game copy and paste: topomojo/copy-paste.md
  - The EXO-Archeologists Solution: cubespace-instructor/1-ins-exo-arch.md
  - The Red Raider Solution: cubespace-instructor/2-ins-red-raider.md
  - The Ancient Ruins Solution: cubespace-instructor/3-ins-ruins.md
  - XENO Cult Solution: cubespace-instructor/4-ins-xeno.md
  - The Museum Solution: cubespace-instructor/5-ins-museum.md
  - Final Challenge Solution: cubespace-instructor/6-ins-final.md
  - Copyright: cubespace-instructor/7-ins-copyright.md

# Copyright
copyright: Copyright &copy; 2023 Carnegie Mellon University
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cmu-sei
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/cmusei
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sei_cmu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/software-engineering-institute/